[versions]
kotlin = "2.0.21"
kotlinxSerializationJson = "1.8.1"
kotlinxCoroutines = "1.8.1"
gson = "2.13.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }